### ISSUE TITLE
Проблема "отрисовки" замечаний после удаления строк

### ISSUE THREAD

**Issue by otymko** [otymko/bslls-connector-for-edt#12]
**EDT**: 2020.2
**Java**: Java11 bellsoft

Пока не понятно в чем проблема:
![image](https://user-images.githubusercontent.com/11651847/99152436-5bccc200-26d4-11eb-81d9-bb5ac594f425.png)
Порядок действий для повторения проблемы:
* Добавляем две пустых строки -> срабатывает проверка в bsl ls, validator ее получает и "рисует"
* Удаляем две строки -> в окне с проблемами замечание ушло, но в коде отрисовка осталась
* Переоткрытие редактора "решает" эту проблему

**Comment by kuzyara** [comment]
ещё непонятная ошибка "Ошибка разбора исходного кода"
![image](https://user-images.githubusercontent.com/2604430/99492555-bef67700-29a8-11eb-9a5f-7596e3b8f9f2.png)

**Comment by nixel2007** [comment]
@kuzyara это у тебя просто код с синтаксической ошибкой. сама ошибка - штатная для бсл лс
https://1c-syntax.github.io/bsl-language-server/diagnostics/ParseError/

**Comment by otymko** [comment]
@kuzyara как раз из-за кеша отрисовки может быть сохранение того, что было в процессе напечатано и проанализировано.

**Comment by asosnoviy** [comment]
Ctrl+s пкм проверить. Вроде тогда исправляется.

**Comment by otymko** [comment]
С версии Sapphire 2020.6.0 Build 2020.6.0.452 проблема ушла и кнопка `Проверить`  отрабатывает корректно.
