### ISSUE TITLE
Отличать замечания ls от замечаний ЕДТ

### ISSUE THREAD

**Issue by asosnoviy** [otymko/bslls-connector-for-edt#15]
При просмотре замечаний хочется понимать кто источник LS или EDT
![image](https://user-images.githubusercontent.com/15638529/99255678-5763ee80-2825-11eb-90b1-b0507d1e80bf.png)

**Comment by asosnoviy** [comment]
Например можно выводить ключ диагностики в конце

**Comment by nixel2007** [comment]
или source

**Comment by otymko** [comment]
Согласен, там было бы "удобнее". Поколдую на неделе

**Comment by otymko** [comment]
В релизе 0.2.1 добавлен префикс `[BSL LS]`
