### ISSUE TITLE
Ошибка при установке LSP4J SDK

### ISSUE THREAD

**Issue by BProg-Gladkov** [otymko/bslls-connector-for-edt#21]
Установлено:
bellsoft_jdk11.0.9_12_windows_amd64_full
1c_edt_distr_offline_2020.6.0_452_windows_x86_64

![image](https://user-images.githubusercontent.com/33430119/102895078-26568980-4475-11eb-8e9e-58c987978087.png)

![image](https://user-images.githubusercontent.com/33430119/102895102-2d7d9780-4475-11eb-8f36-f8d087a9e40f.png)

Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Устанавливаемое программное обеспечение: LSP4J SDK 0.8.1.v20190925-0747 (org.eclipse.lsp4j.sdk.feature.group 0.8.1.v20190925-0747)
  Отсутствующее требование: org.eclipse.lsp4j.websocket 0.8.1.v20190925-0746 (org.eclipse.lsp4j.websocket 0.8.1.v20190925-0746) требует 'java.package; javax.websocket [1.0.0,2.0.0)', но его не удалось найти
  Не возможно удовлетворить зависимость:
    Из: LSP4J SDK 0.8.1.v20190925-0747 (org.eclipse.lsp4j.sdk.feature.group 0.8.1.v20190925-0747)
    Что: org.eclipse.equinox.p2.iu; org.eclipse.lsp4j.websocket [0.8.1.v20190925-0746,0.8.1.v20190925-0746]

**Comment by BProg-Gladkov** [comment]
Заработало.
Проблема была в пробелах или русских буквах в имени пользователя.

**Comment by nixel2007** [comment]
@otymko в всц-плагине для этого есть отдельная проверка и ругань. и свойство с указанием каталога, куда распаковывается бсл лс.

**Comment by otymko** [comment]
@BProg-Gladkov @nixel2007 учту. Создам отдельную досаду на разработку

**Comment by otymko** [comment]
Единственное , что это дефолтная установка плагина

**Comment by myxins** [comment]
Помогла доустановка equinox и lsp4j из вот этого репозитория https://download.eclipse.org/releases/2023-06/202306141000.
