### ISSUE TITLE
Не работает в EDT 2021.1

### ISSUE THREAD

**Issue by artbear** [otymko/bslls-connector-for-edt#27]
Не удается завершить установку, так как не удалось найти один или несколько необходимых элементов.
  Устанавливаемое программное обеспечение: LSP4J SDK 0.8.1.v20190925-0747 (org.eclipse.lsp4j.sdk.feature.group 0.8.1.v20190925-0747)
  Отсутствующее требование: org.eclipse.lsp4j.websocket 0.8.1.v20190925-0746 (org.eclipse.lsp4j.websocket 0.8.1.v20190925-0746) требует 'java.package; javax.websocket [1.0.0,2.0.0)', но его не удалось найти
  Не возможно удовлетворить зависимость:
    Из: LSP4J SDK 0.8.1.v20190925-0747 (org.eclipse.lsp4j.sdk.feature.group 0.8.1.v20190925-0747)
    Что: org.eclipse.equinox.p2.iu; org.eclipse.lsp4j.websocket [0.8.1.v20190925-0746,0.8.1.v20190925-0746]

@otymko

**Comment by otymko** [comment]
@artbear да, пока сборка на 2021.1 только в тестовом варианте. Можно скачать тут -> 
[bsl-lsconnector-0.3.0-SNAPSHOT.zip](https://github.com/otymko/bslls-connector-for-edt/files/6065906/bsl-lsconnector-0.3.0-SNAPSHOT.zip)

**Comment by artbear** [comment]
Да, указанная сборка установилась в 2021.1
Спасибо!
